export enum ActivityType {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    CREATE = 'CREATE',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',

    // TRANSACTIONS RELATED
    DEPOSIT = 'DEPOSIT',
    WITHDRAW = 'WITHDRAW',
    SWAP = 'SWAP',

    // PROFILE RELATED
    UPDATE_PROFILE = 'UPDATE_PROFILE',
    UPDATE_SETTINGS = 'UPDATE_SETTINGS',
    PROFILE_CREATE = 'PROFILE_CREATE',
    PROFILE_UPDATE = 'PROFILE_UPDATE',
    PROFILE_DELETE = 'PROFILE_DELETE',
    PROFILE_UPDATE_SETTINGS = 'PROFILE_UPDATE_SETTINGS',
    PROFILE_UPDATE_EMAIL = 'PROFILE_UPDATE_EMAIL',
    PROFILE_UPDATE_PHONE = 'PROFILE_UPDATE_PHONE',

    // USER RELATED
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_DELETE = 'USER_DELETE',
    USER_UPDATE_BIOMETRIC_SETTINGS = 'USER_UPDATE_BIOMETRIC_SETTINGS',
    USER_UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD',
    USER_UPDATE_EMAIL = 'USER_UPDATE_EMAIL',
}
  
  